Language: 'English'
Bungee: false
Mysql:
  Status: false
  Host: '127.0.0.1'
  Port: 3306
  DatabaseName: 'mydatabase'
  SSLEnabled: false
  AutoReconnect: true
  VerifyServerCertificate: false
  User: 'admin'
  Password: 'not_0123456789'
  TableNameI: 'automaticexecuteItems'
# => <origin+message>~click@SUGGEST_COMMAND@/blubb~hover@SHOW_TEXT@messagepath
# => click@SUGGEST_COMMAND@/blubb
# => hover@SHOW_TEXTt@textpath
# => hover@SHOW_ITEM@mysqlitemname
# => <origin Message>~book@mysqlbookname
Identifier:
  Click: 'click'
  Hover: 'hover'
  Book: 'book'
Seperator:
  BetweenFunction: '~'
  WhithinFuction: '@'
  Space: '+'
  HoverNewLine: '~!~'